#!/usr/bin/env python3
"""Summarize collected SMAC progress rows as Markdown."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


def as_float(row: dict[str, str], key: str) -> float:
    try:
        return float(row[key])
    except (KeyError, ValueError) as exc:
        raise SystemExit(f"Invalid numeric value for {key}: {row}") from exc


def mode_for_exp(exp_name: str) -> str:
    if "pilot" in exp_name:
        return "pilot"
    if "smoke" in exp_name:
        return "smoke"
    if "full" in exp_name:
        return "full"
    return "unknown"


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8") as file:
        return list(csv.DictReader(file))


def summarize_runs(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    grouped: dict[tuple[str, str, str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[(row["map"], row["algo"], row["exp"], row["run"])].append(row)

    summaries: list[dict[str, str]] = []
    for (map_name, algo, exp, run), run_rows in sorted(grouped.items()):
        run_rows.sort(key=lambda item: as_float(item, "step"))
        final = run_rows[-1]
        best_reward = max(as_float(row, "eval_average_episode_reward") for row in run_rows)
        best_win_rate = max(as_float(row, "eval_win_rate") for row in run_rows)
        summaries.append(
            {
                "mode": mode_for_exp(exp),
                "map": map_name,
                "algo": algo,
                "exp": exp,
                "run": run,
                "rows": str(len(run_rows)),
                "final_step": f"{as_float(final, 'step'):.0f}",
                "final_reward": f"{as_float(final, 'eval_average_episode_reward'):.4f}",
                "final_win_rate": f"{as_float(final, 'eval_win_rate'):.4f}",
                "best_reward": f"{best_reward:.4f}",
                "best_win_rate": f"{best_win_rate:.4f}",
            }
        )
    return summaries


def render_markdown(summaries: list[dict[str, str]], source: Path) -> str:
    lines = [
        "# SMAC Progress Summary",
        "",
        f"Source: `{source}`",
        "",
        "| Mode | Map | Algo | Rows | Final step | Final reward | Final win rate | Best reward | Best win rate |",
        "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for summary in summaries:
        lines.append(
            "| {mode} | `{map}` | {algo} | {rows} | {final_step} | {final_reward} | {final_win_rate} | {best_reward} | {best_win_rate} |".format(
                **summary
            )
        )
    lines.extend(
        [
            "",
            "Notes:",
            "",
            "- `smoke` rows verify the end-to-end training, logging, collection and plotting pipeline.",
            "- `pilot` rows cover the complete MAPPO/HAPPO x `3s5z`/`8m_vs_9m` matrix at 10000 environment steps.",
            "- `full` rows are checkpoints from HARL tuned configs; they are final performance evidence only after the full run completes.",
            "- Smoke, pilot and early full checkpoints are not final performance evidence; full HARL tuned configs use 20000000 environment steps.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("results/processed/progress_summary.csv"),
        help="CSV generated by scripts/collect_progress.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/processed/progress_summary.md"),
        help="Markdown summary output path.",
    )
    args = parser.parse_args()

    rows = load_rows(args.input)
    summaries = summarize_runs(rows)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_markdown(summaries, args.input), encoding="utf-8")
    print(f"input_rows={len(rows)}")
    print(f"written_runs={len(summaries)}")
    print(f"output={args.output}")


if __name__ == "__main__":
    main()
